/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PostSitemapDotxmlRouteImport } from './routes/post-sitemap[.]xml'
import { Route as PageSitemapDotxmlRouteImport } from './routes/page-sitemap[.]xml'
import { Route as LocalSitemapDotxmlRouteImport } from './routes/local-sitemap[.]xml'
import { Route as LocacaoDeBetoneirasRouteImport } from './routes/locacao-de-betoneiras'
import { Route as LocacaoCaminhaoBetoneiraRouteImport } from './routes/locacao-caminhao-betoneira'
import { Route as EntregaERetiradaDeBetoneiraRouteImport } from './routes/entrega-e-retirada-de-betoneira'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComprarBetoneiraRouteImport } from './routes/comprar-betoneira'
import { Route as CaminhaoBetoneiraRouteImport } from './routes/caminhao-betoneira'
import { Route as Betoneira400lGasolinaRouteImport } from './routes/betoneira-400l-gasolina'
import { Route as Betoneira400lEletricaRouteImport } from './routes/betoneira-400l-eletrica'
import { Route as Betoneira250lRouteImport } from './routes/betoneira-250l'
import { Route as Betoneira150lRouteImport } from './routes/betoneira-150l'
import { Route as Betoneira120lRouteImport } from './routes/betoneira-120l'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSitemapDotxmlRoute = PostSitemapDotxmlRouteImport.update({
  id: '/post-sitemap.xml',
  path: '/post-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSitemapDotxmlRoute = PageSitemapDotxmlRouteImport.update({
  id: '/page-sitemap.xml',
  path: '/page-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalSitemapDotxmlRoute = LocalSitemapDotxmlRouteImport.update({
  id: '/local-sitemap.xml',
  path: '/local-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocacaoDeBetoneirasRoute = LocacaoDeBetoneirasRouteImport.update({
  id: '/locacao-de-betoneiras',
  path: '/locacao-de-betoneiras',
  getParentRoute: () => rootRouteImport,
} as any)
const LocacaoCaminhaoBetoneiraRoute =
  LocacaoCaminhaoBetoneiraRouteImport.update({
    id: '/locacao-caminhao-betoneira',
    path: '/locacao-caminhao-betoneira',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntregaERetiradaDeBetoneiraRoute =
  EntregaERetiradaDeBetoneiraRouteImport.update({
    id: '/entrega-e-retirada-de-betoneira',
    path: '/entrega-e-retirada-de-betoneira',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarBetoneiraRoute = ComprarBetoneiraRouteImport.update({
  id: '/comprar-betoneira',
  path: '/comprar-betoneira',
  getParentRoute: () => rootRouteImport,
} as any)
const CaminhaoBetoneiraRoute = CaminhaoBetoneiraRouteImport.update({
  id: '/caminhao-betoneira',
  path: '/caminhao-betoneira',
  getParentRoute: () => rootRouteImport,
} as any)
const Betoneira400lGasolinaRoute = Betoneira400lGasolinaRouteImport.update({
  id: '/betoneira-400l-gasolina',
  path: '/betoneira-400l-gasolina',
  getParentRoute: () => rootRouteImport,
} as any)
const Betoneira400lEletricaRoute = Betoneira400lEletricaRouteImport.update({
  id: '/betoneira-400l-eletrica',
  path: '/betoneira-400l-eletrica',
  getParentRoute: () => rootRouteImport,
} as any)
const Betoneira250lRoute = Betoneira250lRouteImport.update({
  id: '/betoneira-250l',
  path: '/betoneira-250l',
  getParentRoute: () => rootRouteImport,
} as any)
const Betoneira150lRoute = Betoneira150lRouteImport.update({
  id: '/betoneira-150l',
  path: '/betoneira-150l',
  getParentRoute: () => rootRouteImport,
} as any)
const Betoneira120lRoute = Betoneira120lRouteImport.update({
  id: '/betoneira-120l',
  path: '/betoneira-120l',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/betoneira-120l': typeof Betoneira120lRoute
  '/betoneira-150l': typeof Betoneira150lRoute
  '/betoneira-250l': typeof Betoneira250lRoute
  '/betoneira-400l-eletrica': typeof Betoneira400lEletricaRoute
  '/betoneira-400l-gasolina': typeof Betoneira400lGasolinaRoute
  '/caminhao-betoneira': typeof CaminhaoBetoneiraRoute
  '/comprar-betoneira': typeof ComprarBetoneiraRoute
  '/contato': typeof ContatoRoute
  '/entrega-e-retirada-de-betoneira': typeof EntregaERetiradaDeBetoneiraRoute
  '/locacao-caminhao-betoneira': typeof LocacaoCaminhaoBetoneiraRoute
  '/locacao-de-betoneiras': typeof LocacaoDeBetoneirasRoute
  '/local-sitemap.xml': typeof LocalSitemapDotxmlRoute
  '/page-sitemap.xml': typeof PageSitemapDotxmlRoute
  '/post-sitemap.xml': typeof PostSitemapDotxmlRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/betoneira-120l': typeof Betoneira120lRoute
  '/betoneira-150l': typeof Betoneira150lRoute
  '/betoneira-250l': typeof Betoneira250lRoute
  '/betoneira-400l-eletrica': typeof Betoneira400lEletricaRoute
  '/betoneira-400l-gasolina': typeof Betoneira400lGasolinaRoute
  '/caminhao-betoneira': typeof CaminhaoBetoneiraRoute
  '/comprar-betoneira': typeof ComprarBetoneiraRoute
  '/contato': typeof ContatoRoute
  '/entrega-e-retirada-de-betoneira': typeof EntregaERetiradaDeBetoneiraRoute
  '/locacao-caminhao-betoneira': typeof LocacaoCaminhaoBetoneiraRoute
  '/locacao-de-betoneiras': typeof LocacaoDeBetoneirasRoute
  '/local-sitemap.xml': typeof LocalSitemapDotxmlRoute
  '/page-sitemap.xml': typeof PageSitemapDotxmlRoute
  '/post-sitemap.xml': typeof PostSitemapDotxmlRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/betoneira-120l': typeof Betoneira120lRoute
  '/betoneira-150l': typeof Betoneira150lRoute
  '/betoneira-250l': typeof Betoneira250lRoute
  '/betoneira-400l-eletrica': typeof Betoneira400lEletricaRoute
  '/betoneira-400l-gasolina': typeof Betoneira400lGasolinaRoute
  '/caminhao-betoneira': typeof CaminhaoBetoneiraRoute
  '/comprar-betoneira': typeof ComprarBetoneiraRoute
  '/contato': typeof ContatoRoute
  '/entrega-e-retirada-de-betoneira': typeof EntregaERetiradaDeBetoneiraRoute
  '/locacao-caminhao-betoneira': typeof LocacaoCaminhaoBetoneiraRoute
  '/locacao-de-betoneiras': typeof LocacaoDeBetoneirasRoute
  '/local-sitemap.xml': typeof LocalSitemapDotxmlRoute
  '/page-sitemap.xml': typeof PageSitemapDotxmlRoute
  '/post-sitemap.xml': typeof PostSitemapDotxmlRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/betoneira-120l'
    | '/betoneira-150l'
    | '/betoneira-250l'
    | '/betoneira-400l-eletrica'
    | '/betoneira-400l-gasolina'
    | '/caminhao-betoneira'
    | '/comprar-betoneira'
    | '/contato'
    | '/entrega-e-retirada-de-betoneira'
    | '/locacao-caminhao-betoneira'
    | '/locacao-de-betoneiras'
    | '/local-sitemap.xml'
    | '/page-sitemap.xml'
    | '/post-sitemap.xml'
    | '/privacidade'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/betoneira-120l'
    | '/betoneira-150l'
    | '/betoneira-250l'
    | '/betoneira-400l-eletrica'
    | '/betoneira-400l-gasolina'
    | '/caminhao-betoneira'
    | '/comprar-betoneira'
    | '/contato'
    | '/entrega-e-retirada-de-betoneira'
    | '/locacao-caminhao-betoneira'
    | '/locacao-de-betoneiras'
    | '/local-sitemap.xml'
    | '/page-sitemap.xml'
    | '/post-sitemap.xml'
    | '/privacidade'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/betoneira-120l'
    | '/betoneira-150l'
    | '/betoneira-250l'
    | '/betoneira-400l-eletrica'
    | '/betoneira-400l-gasolina'
    | '/caminhao-betoneira'
    | '/comprar-betoneira'
    | '/contato'
    | '/entrega-e-retirada-de-betoneira'
    | '/locacao-caminhao-betoneira'
    | '/locacao-de-betoneiras'
    | '/local-sitemap.xml'
    | '/page-sitemap.xml'
    | '/post-sitemap.xml'
    | '/privacidade'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  Betoneira120lRoute: typeof Betoneira120lRoute
  Betoneira150lRoute: typeof Betoneira150lRoute
  Betoneira250lRoute: typeof Betoneira250lRoute
  Betoneira400lEletricaRoute: typeof Betoneira400lEletricaRoute
  Betoneira400lGasolinaRoute: typeof Betoneira400lGasolinaRoute
  CaminhaoBetoneiraRoute: typeof CaminhaoBetoneiraRoute
  ComprarBetoneiraRoute: typeof ComprarBetoneiraRoute
  ContatoRoute: typeof ContatoRoute
  EntregaERetiradaDeBetoneiraRoute: typeof EntregaERetiradaDeBetoneiraRoute
  LocacaoCaminhaoBetoneiraRoute: typeof LocacaoCaminhaoBetoneiraRoute
  LocacaoDeBetoneirasRoute: typeof LocacaoDeBetoneirasRoute
  LocalSitemapDotxmlRoute: typeof LocalSitemapDotxmlRoute
  PageSitemapDotxmlRoute: typeof PageSitemapDotxmlRoute
  PostSitemapDotxmlRoute: typeof PostSitemapDotxmlRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ServicosRoute: typeof ServicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-sitemap.xml': {
      id: '/post-sitemap.xml'
      path: '/post-sitemap.xml'
      fullPath: '/post-sitemap.xml'
      preLoaderRoute: typeof PostSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-sitemap.xml': {
      id: '/page-sitemap.xml'
      path: '/page-sitemap.xml'
      fullPath: '/page-sitemap.xml'
      preLoaderRoute: typeof PageSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-sitemap.xml': {
      id: '/local-sitemap.xml'
      path: '/local-sitemap.xml'
      fullPath: '/local-sitemap.xml'
      preLoaderRoute: typeof LocalSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locacao-de-betoneiras': {
      id: '/locacao-de-betoneiras'
      path: '/locacao-de-betoneiras'
      fullPath: '/locacao-de-betoneiras'
      preLoaderRoute: typeof LocacaoDeBetoneirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locacao-caminhao-betoneira': {
      id: '/locacao-caminhao-betoneira'
      path: '/locacao-caminhao-betoneira'
      fullPath: '/locacao-caminhao-betoneira'
      preLoaderRoute: typeof LocacaoCaminhaoBetoneiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega-e-retirada-de-betoneira': {
      id: '/entrega-e-retirada-de-betoneira'
      path: '/entrega-e-retirada-de-betoneira'
      fullPath: '/entrega-e-retirada-de-betoneira'
      preLoaderRoute: typeof EntregaERetiradaDeBetoneiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar-betoneira': {
      id: '/comprar-betoneira'
      path: '/comprar-betoneira'
      fullPath: '/comprar-betoneira'
      preLoaderRoute: typeof ComprarBetoneiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caminhao-betoneira': {
      id: '/caminhao-betoneira'
      path: '/caminhao-betoneira'
      fullPath: '/caminhao-betoneira'
      preLoaderRoute: typeof CaminhaoBetoneiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betoneira-400l-gasolina': {
      id: '/betoneira-400l-gasolina'
      path: '/betoneira-400l-gasolina'
      fullPath: '/betoneira-400l-gasolina'
      preLoaderRoute: typeof Betoneira400lGasolinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betoneira-400l-eletrica': {
      id: '/betoneira-400l-eletrica'
      path: '/betoneira-400l-eletrica'
      fullPath: '/betoneira-400l-eletrica'
      preLoaderRoute: typeof Betoneira400lEletricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betoneira-250l': {
      id: '/betoneira-250l'
      path: '/betoneira-250l'
      fullPath: '/betoneira-250l'
      preLoaderRoute: typeof Betoneira250lRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betoneira-150l': {
      id: '/betoneira-150l'
      path: '/betoneira-150l'
      fullPath: '/betoneira-150l'
      preLoaderRoute: typeof Betoneira150lRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betoneira-120l': {
      id: '/betoneira-120l'
      path: '/betoneira-120l'
      fullPath: '/betoneira-120l'
      preLoaderRoute: typeof Betoneira120lRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  Betoneira120lRoute: Betoneira120lRoute,
  Betoneira150lRoute: Betoneira150lRoute,
  Betoneira250lRoute: Betoneira250lRoute,
  Betoneira400lEletricaRoute: Betoneira400lEletricaRoute,
  Betoneira400lGasolinaRoute: Betoneira400lGasolinaRoute,
  CaminhaoBetoneiraRoute: CaminhaoBetoneiraRoute,
  ComprarBetoneiraRoute: ComprarBetoneiraRoute,
  ContatoRoute: ContatoRoute,
  EntregaERetiradaDeBetoneiraRoute: EntregaERetiradaDeBetoneiraRoute,
  LocacaoCaminhaoBetoneiraRoute: LocacaoCaminhaoBetoneiraRoute,
  LocacaoDeBetoneirasRoute: LocacaoDeBetoneirasRoute,
  LocalSitemapDotxmlRoute: LocalSitemapDotxmlRoute,
  PageSitemapDotxmlRoute: PageSitemapDotxmlRoute,
  PostSitemapDotxmlRoute: PostSitemapDotxmlRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ServicosRoute: ServicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
