/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComprarBetoneiraRouteImport } from './routes/comprar-betoneira'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlugarBetoneiraEmOsascoBairroRouteImport } from './routes/alugar-betoneira-em-osasco.$bairro'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarBetoneiraRoute = ComprarBetoneiraRouteImport.update({
  id: '/comprar-betoneira',
  path: '/comprar-betoneira',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlugarBetoneiraEmOsascoBairroRoute =
  AlugarBetoneiraEmOsascoBairroRouteImport.update({
    id: '/alugar-betoneira-em-osasco/$bairro',
    path: '/alugar-betoneira-em-osasco/$bairro',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comprar-betoneira': typeof ComprarBetoneiraRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/alugar-betoneira-em-osasco/$bairro': typeof AlugarBetoneiraEmOsascoBairroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comprar-betoneira': typeof ComprarBetoneiraRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/alugar-betoneira-em-osasco/$bairro': typeof AlugarBetoneiraEmOsascoBairroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comprar-betoneira': typeof ComprarBetoneiraRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/alugar-betoneira-em-osasco/$bairro': typeof AlugarBetoneiraEmOsascoBairroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comprar-betoneira'
    | '/contato'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/alugar-betoneira-em-osasco/$bairro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comprar-betoneira'
    | '/contato'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/alugar-betoneira-em-osasco/$bairro'
  id:
    | '__root__'
    | '/'
    | '/comprar-betoneira'
    | '/contato'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/alugar-betoneira-em-osasco/$bairro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComprarBetoneiraRoute: typeof ComprarBetoneiraRoute
  ContatoRoute: typeof ContatoRoute
  ServicosRoute: typeof ServicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  AlugarBetoneiraEmOsascoBairroRoute: typeof AlugarBetoneiraEmOsascoBairroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar-betoneira': {
      id: '/comprar-betoneira'
      path: '/comprar-betoneira'
      fullPath: '/comprar-betoneira'
      preLoaderRoute: typeof ComprarBetoneiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alugar-betoneira-em-osasco/$bairro': {
      id: '/alugar-betoneira-em-osasco/$bairro'
      path: '/alugar-betoneira-em-osasco/$bairro'
      fullPath: '/alugar-betoneira-em-osasco/$bairro'
      preLoaderRoute: typeof AlugarBetoneiraEmOsascoBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComprarBetoneiraRoute: ComprarBetoneiraRoute,
  ContatoRoute: ContatoRoute,
  ServicosRoute: ServicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  AlugarBetoneiraEmOsascoBairroRoute: AlugarBetoneiraEmOsascoBairroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
